version: "3"

services:
  postgres:
    image: "postgres:9.5"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  redis:
    image: 'redis:6.0.4'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'

  website:
    depends_on:
      - "postgres"
      - 'redis'
      - "mailcatcher"
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/onebitchat
      - bundle_cache:/bundle_cache
    environment:
      - BUNDLE_PATH=/bundle_cache

  bundle_cache:
    image: busybox
    volumes:
      - bundle_cache:/bundle_cache

  mailcatcher:
    image: zolweb/docker-mailcatcher:latest
    ports:
      - "1025:1025"
      - "1080:1080"

volumes:
  postgres:
  redis:
  bundle_cache:
